# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

1.26.3


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
array = np.zeros(10)
print(f"Memory size of the array: {array.nbytes} bytes")

Memory size of the array: 80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
!python -c "import numpy as np; help(np.add)"

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
matrix1 = np.arange(9).reshape(3, 3)
print(matrix1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
a = np.array([1, 2, 0, 0, 4, 0])
b = np.nonzero(a)
print(b)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
random_3x3x3 = np.random.random((3, 3, 3))
print(random_3x3x3)

[[[0.85050077 0.77875418 0.6801064 ]
  [0.4461076  0.65189056 0.56972738]
  [0.92342383 0.3944157  0.12596806]]

 [[0.61810882 0.71479816 0.51159683]
  [0.45749471 0.30210751 0.82225042]
  [0.03847752 0.14361112 0.08893805]]

 [[0.23448913 0.85932606 0.89484101]
  [0.54684006 0.22066123 0.87936288]
  [0.16527094 0.95918205 0.55467131]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("Minimum value:",min_value)
print("Maximum value:", max_value)

Minimum value: 0.028761902028352715
Maximum value: 0.9936046249546272


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
random_vector = np.random.random(30)
mean_value = random_vector.mean()
print("Random vector:", random_vector)
print("Mean value:", mean_value)

Random vector: [0.90009221 0.26766822 0.56935373 0.42594737 0.52956413 0.65626278
 0.34015147 0.36279394 0.05526738 0.81256618 0.33082657 0.61146518
 0.97796801 0.66581513 0.67702217 0.78141997 0.18583739 0.77487891
 0.91397835 0.33436504 0.06260297 0.71229057 0.1033675  0.79293573
 0.5731698  0.18378614 0.34775641 0.34281217 0.18465546 0.2084961 ]
Mean value: 0.4895038996089962


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
array = np.ones((4, 4))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
array_with_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(array_with_border)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
np.diag(np.arange(1, 5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
index = np.unravel_index(100, (6, 7, 8))
print(index)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
checkerboard_tile = np.tile([[0, 1], [1, 0]], (4, 4))
print(checkerboard_tile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
random_matrix = np.random.random((5, 5))
normalized_matrix = (random_matrix - random_matrix.min()) / (random_matrix.max() - random_matrix.min())
print("Random matrix:\n", random_matrix)
print("Normalized matrix:\n", normalized_matrix)

Random matrix:
 [[0.25877987 0.53131735 0.94107617 0.74135793 0.02653141]
 [0.87010215 0.25953003 0.76877841 0.53374751 0.66383523]
 [0.80709428 0.78835138 0.69817816 0.2653101  0.7284582 ]
 [0.90418064 0.02001465 0.45634223 0.4809847  0.10042697]
 [0.72834063 0.66756413 0.50430142 0.17560482 0.7673446 ]]
Normalized matrix:
 [[0.25922831 0.55512329 1.         0.78316515 0.00707527]
 [0.92294324 0.26004276 0.81293567 0.55776172 0.69899846]
 [0.85453535 0.83418612 0.73628471 0.26631821 0.76915986]
 [0.95994239 0.         0.47372251 0.50047694 0.08730396]
 [0.76903222 0.70304694 0.52579199 0.16892484 0.81137897]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
color_dtype = np.dtype([('r', np.ubyte), ('g', np.ubyte), ('b', np.ubyte), ('a', np.ubyte)])
print(color_dtype)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
matrix_5x3 = np.random.random((5, 3))
matrix_3x2 = np.random.random((3, 2))
result = matrix_5x3 @ matrix_3x2
print("5x3 Matrix:\n", matrix_5x3)
print("3x2 Matrix:\n", matrix_3x2)
print("Resultant Matrix:\n", result)

5x3 Matrix:
 [[0.85790016 0.06277621 0.51551341]
 [0.14134341 0.45879621 0.71153644]
 [0.41261666 0.97286142 0.9913452 ]
 [0.39428558 0.09202165 0.10798218]
 [0.44120847 0.30495796 0.02397527]]
3x2 Matrix:
 [[0.1930559  0.98402615]
 [0.90228862 0.19043225]
 [0.5127043  0.74748516]]
Resultant Matrix:
 [[0.48657089 1.24148943]
 [0.80606158 0.75831813]
 [1.46572683 1.3323056 ]
 [0.21451218 0.48622629]
 [0.37263022 0.51015567]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
Z = np.arange(11)
Z[(Z > 3) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
try:
    print("Z**Z:", Z**Z)
    print("legal")
except Exception as e:
    print("Z**Z: Error -", e)

try:
    print("2 << Z >> 2:", 2 << Z >> 2)
    print("legal")
except Exception as e:
    print("2 << Z >> 2: Error -", e)

try:
    print("Z <- Z:", Z <- Z)
    print("legal")
except Exception as e:
    print("Z <- Z: Error -", e)

try:
    print("1j*Z:", 1j*Z)
    print("legal")
except Exception as e:
    print("1j*Z: Error -", e)

try:
    print("Z/1/1:", Z/1/1)
    print("legal")
except Exception as e:
    print("Z/1/1: Error -", e)

try:
    print("Z<Z>Z:", Z<Z>Z)
    print("legal")
except Exception as e:
    print("Z<Z>Z: Error -", e)

Z**Z: Error - Integers to negative integer powers are not allowed.
2 << Z >> 2: [  0   1   2   4   0   0   0   0 128 256 512]
legal
Z <- Z: [False False False False  True  True  True  True False False False]
legal
1j*Z: [ 0. +0.j  0. +1.j  0. +2.j  0. +3.j -0. -4.j -0. -5.j -0. -6.j -0. -7.j
  0. +8.j  0. +9.j  0.+10.j]
legal
Z/1/1: [ 0.  1.  2.  3. -4. -5. -6. -7.  8.  9. 10.]
legal
Z<Z>Z: Error - The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
print(np.array(0) / np.array(0))  
print(np.array(0) // np.array(0)) 
print(np.array([np.nan]).astype(int).astype(float)) 

nan
0
[-2.14748365e+09]


C:\Users\197as\AppData\Local\Temp\ipykernel_18496\1833778177.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\197as\AppData\Local\Temp\ipykernel_18496\1833778177.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\197as\AppData\Local\Temp\ipykernel_18496\1833778177.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
float_array = np.random.uniform(-10, 10, 10)
rounded_array = np.copysign(np.ceil(np.abs(float_array)), float_array)
print("Original array:", float_array)
print("Rounded array:", rounded_array)

Original array: [-0.49342273 -6.22199143 -7.99040463 -4.92338045  2.93010122 -5.44175736
 -0.71023316 -5.77895578  4.5735873  -5.94748844]
Rounded array: [-1. -7. -8. -5.  3. -6. -1. -6.  5. -6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
common_values = np.intersect1d(array1, array2)
print("Common values:", common_values)

Common values: [3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [31]:
np.seterr(all='ignore')
print(np.sqrt(-1))

nan


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
result = np.sqrt(-1) == np.emath.sqrt(-1)
print(result)

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2025-04-21
Today: 2025-04-22
Tomorrow: 2025-04-23


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [35]:
A = np.ones(3)  
B = np.ones(3) * 2  

A += B  
A *= -0.5  

print(A)

[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [36]:
random_array = np.random.uniform(0, 10, 10)

integer_part_1 = np.floor(random_array)

integer_part_2 = np.trunc(random_array)

integer_part_3 = random_array.astype(int)

integer_part_4 = np.vectorize(int)(random_array)

print("Original array:", random_array)
print("Integer part (Method 1 - floor):", integer_part_1)
print("Integer part (Method 2 - trunc):", integer_part_2)
print("Integer part (Method 3 - astype):", integer_part_3)
print("Integer part (Method 4 - vectorize):", integer_part_4)

Original array: [8.91069761 0.28028296 1.29406822 9.48057243 1.00487145 4.40526164
 0.51209269 5.61071427 7.47411542 1.06729087]
Integer part (Method 1 - floor): [8. 0. 1. 9. 1. 4. 0. 5. 7. 1.]
Integer part (Method 2 - trunc): [8. 0. 1. 9. 1. 4. 0. 5. 7. 1.]
Integer part (Method 3 - astype): [8 0 1 9 1 4 0 5 7 1]
Integer part (Method 4 - vectorize): [8 0 1 9 1 4 0 5 7 1]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
matrix = np.arange(5).reshape(1, -1) * np.ones((5, 1), dtype=int)
print(matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [38]:
matrix = np.array(list(range(10)))
print(matrix)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [39]:
vector = np.linspace(0, 1, 12)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [40]:
random_vector = np.random.random(10)
sorted_vector = np.sort(random_vector)
print("Random vector:", random_vector)
print("Sorted vector:", sorted_vector)

Random vector: [0.07981081 0.55328718 0.22181875 0.29801649 0.24055403 0.70770479
 0.38246732 0.25933962 0.20012999 0.81143209]
Sorted vector: [0.07981081 0.20012999 0.22181875 0.24055403 0.25933962 0.29801649
 0.38246732 0.55328718 0.70770479 0.81143209]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [41]:
small_array = np.array([1, 2, 3, 4, 5])
result = sum(small_array)
print("Sum of the array:", result)

Sum of the array: 15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [42]:
import numpy as np

A = np.random.rand(5)  
B = np.random.rand(5)

are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)
print("Are A and B equal?", are_equal)

Array A: [0.93443082 0.81250295 0.96688136 0.65723724 0.87658019]
Array B: [0.51810839 0.2809836  0.92072823 0.09225792 0.586608  ]
Are A and B equal? False


#### 43. Make an array immutable (read-only) (★★☆)

In [43]:
import numpy as np
A = np.random.rand(5)
A.flags.writeable = False
print("Array A:", A)
try:
    A[0] = 10
except ValueError as e:
    print("Error:", e)

Array A: [0.33202862 0.93606847 0.50484846 0.75221175 0.95801523]
Error: assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [44]:
import numpy as np
A = np.random.rand(5)
A.flags.writeable = False
print("Array A:", A)
try:
    A[0] = 10
except ValueError as e:
    print("Error:", e)

Array A: [0.43821714 0.73464836 0.6371777  0.77912282 0.92685233]
Error: assignment destination is read-only


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [45]:
import numpy as np
vector = np.random.rand(10)
max_index = np.argmax(vector)
vector[max_index] = 0

print("Modified vector:", vector)

Modified vector: [0.914008   0.52468987 0.62559684 0.43751713 0.07321696 0.
 0.84708063 0.13026195 0.82171195 0.71460156]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [46]:
import numpy as np
grid_size = 5  
structured_array = np.zeros((grid_size, grid_size), dtype=[('x', float), ('y', float)])
structured_array['x'], structured_array['y'] = np.meshgrid(
    np.linspace(0, 1, grid_size), 
    np.linspace(0, 1, grid_size)
)

print("Structured array with x and y coordinates:")
print(structured_array)

Structured array with x and y coordinates:
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [47]:
import numpy as np

X = np.random.rand(5)  
Y = np.random.rand(5)  

C = 1.0 / (X[:, None] - Y[None, :])

print("Array X:", X)
print("Array Y:", Y)
print("Cauchy Matrix C:")
print(C)

Array X: [0.32909904 0.08783643 0.05510831 0.99980769 0.05004334]
Array Y: [0.32942481 0.91360435 0.50535522 0.23493411 0.36671033]
Cauchy Matrix C:
[[-3.06963213e+03 -1.71084844e+00 -5.67355985e+00  1.06196649e+01
  -2.65877641e+01]
 [-4.13927189e+00 -1.21099400e+00 -2.39510177e+00 -6.79820373e+00
  -3.58585014e+00]
 [-3.64542420e+00 -1.16482774e+00 -2.22100359e+00 -5.56093744e+00
  -3.20922190e+00]
 [ 1.49168488e+00  1.16004792e+01  2.02243910e+00  1.30740560e+00
   1.57953588e+00]
 [-3.57933543e+00 -1.15799577e+00 -2.19629673e+00 -5.40859882e+00
  -3.15789155e+00]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [48]:
import numpy as np

# List of NumPy scalar types
scalar_types = [np.int8, np.int16, np.int32, np.int64, 
                np.uint8, np.uint16, np.uint32, np.uint64, 
                np.float16, np.float32, np.float64]

# Print the minimum and maximum representable values for each type
for scalar in scalar_types:
    print(f"{scalar.__name__}:")
    print(f"  Min: {np.iinfo(scalar).min if np.issubdtype(scalar, np.integer) else np.finfo(scalar).min}")
    print(f"  Max: {np.iinfo(scalar).max if np.issubdtype(scalar, np.integer) else np.finfo(scalar).max}")

int8:
  Min: -128
  Max: 127
int16:
  Min: -32768
  Max: 32767
int32:
  Min: -2147483648
  Max: 2147483647
int64:
  Min: -9223372036854775808
  Max: 9223372036854775807
uint8:
  Min: 0
  Max: 255
uint16:
  Min: 0
  Max: 65535
uint32:
  Min: 0
  Max: 4294967295
uint64:
  Min: 0
  Max: 18446744073709551615
float16:
  Min: -65504.0
  Max: 65504.0
float32:
  Min: -3.4028234663852886e+38
  Max: 3.4028234663852886e+38
float64:
  Min: -1.7976931348623157e+308
  Max: 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [49]:
import numpy as np
array = np.arange(10000).reshape(100, 100)
np.set_printoptions(threshold=np.inf)
print(array)

[[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
    14   15   16   17   18   19   20   21   22   23   24   25   26   27
    28   29   30   31   32   33   34   35   36   37   38   39   40   41
    42   43   44   45   46   47   48   49   50   51   52   53   54   55
    56   57   58   59   60   61   62   63   64   65   66   67   68   69
    70   71   72   73   74   75   76   77   78   79   80   81   82   83
    84   85   86   87   88   89   90   91   92   93   94   95   96   97
    98   99]
 [ 100  101  102  103  104  105  106  107  108  109  110  111  112  113
   114  115  116  117  118  119  120  121  122  123  124  125  126  127
   128  129  130  131  132  133  134  135  136  137  138  139  140  141
   142  143  144  145  146  147  148  149  150  151  152  153  154  155
   156  157  158  159  160  161  162  163  164  165  166  167  168  169
   170  171  172  173  174  175  176  177  178  179  180  181  182  183
   184  185  186  187  188  189  190  191  192  193

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [50]:
import numpy as np
vector = np.random.rand(10)
scalar = 0.5

closest_value = vector[np.abs(vector - scalar).argmin()]

print("Vector:", vector)
print("Scalar:", scalar)
print("Closest value:", closest_value)

Vector: [0.08345108 0.47368685 0.12709712 0.51414119 0.9469165  0.77299289
 0.88322663 0.06303182 0.9083874  0.9906937 ]
Scalar: 0.5
Closest value: 0.5141411853868224


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [51]:
import numpy as np
dtype = [('position', [('x', float), ('y', float)]), 
         ('color', [('r', float), ('g', float), ('b', float)])]

structured_array = np.zeros(5, dtype=dtype)  

structured_array['position']['x'] = np.random.rand(5)
structured_array['position']['y'] = np.random.rand(5)
structured_array['color']['r'] = np.random.rand(5)
structured_array['color']['g'] = np.random.rand(5)
structured_array['color']['b'] = np.random.rand(5)

print("Structured array:")
print(structured_array)

Structured array:
[((0.59292723, 0.765542  ), (0.84234416, 0.38473898, 0.35289804))
 ((0.17926062, 0.91005152), (0.29496667, 0.30819635, 0.22232885))
 ((0.75435977, 0.8414071 ), (0.49859149, 0.05331836, 0.28054806))
 ((0.39752325, 0.71838298), (0.81151738, 0.27322934, 0.80011463))
 ((0.9854995 , 0.16386731), (0.3712758 , 0.84923409, 0.4266671 ))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [52]:
import numpy as np
from scipy.spatial import distance
coordinates = np.random.rand(100, 2)

distances = distance.cdist(coordinates, coordinates, metric='euclidean')

print("Pairwise distances:")
print(distances)

Pairwise distances:
[[0.         0.34421584 0.71977236 0.86285817 0.30399441 0.82810009
  0.69526839 0.11923901 0.82927885 0.04241954 0.77749919 0.64399021
  0.73352608 0.64478773 0.53251725 0.90624858 0.29213932 0.43018198
  0.19237825 0.62448794 0.75975804 0.40797674 0.82860204 0.2106749
  0.24733984 0.53953106 0.17278413 0.25010961 0.67800262 0.22033745
  0.28175626 0.31070712 0.23405386 0.38473385 0.05449807 0.63567677
  0.58697728 0.37533333 0.79242934 0.89173956 0.65196721 0.29786723
  0.699536   0.94022843 1.00022567 0.67384068 0.57177234 0.29181074
  0.65161674 0.566395   0.31473014 0.56776564 0.86195234 0.64365991
  0.63665577 0.84066561 0.40606502 0.50270557 0.67553544 0.64907771
  0.71302506 0.50899548 0.68068275 0.66187546 0.81136749 0.61340685
  0.48884022 0.8759056  0.36742486 0.10471613 0.51455998 0.24086914
  0.12682613 0.59903699 0.44455302 0.1787674  0.106724   1.01881658
  0.70016415 0.41456643 0.45186575 0.31458904 0.48487134 0.36601208
  0.58495614 0.71798826 0.358

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [53]:
import numpy as np

float_array = np.random.rand(10).astype(np.float32)
print("Original float array:", float_array)

float_array = float_array.astype(np.int32, copy=False)
print("Converted integer array:", float_array)

Original float array: [0.03641002 0.4912967  0.30162713 0.97115743 0.731054   0.03670176
 0.14135218 0.06884317 0.99231493 0.8739824 ]
Converted integer array: [0 0 0 0 0 0 0 0 0 0]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [55]:
import numpy as np
from io import StringIO

file_content = """1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11"""

data = np.genfromtxt(StringIO(file_content), delimiter=",", dtype=float)

print("Data from the file:")
print(data)

Data from the file:
[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [56]:
import numpy as np

array = np.array([[1, 2], [3, 4]])
for index, value in np.ndenumerate(array):
    print(index, value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [57]:
x, y = np.meshgrid(np.linspace(-1, 1, grid_size), np.linspace(-1, 1, grid_size))
gaussian_array = np.exp(-(x**2 + y**2) / 0.1)
print("2D Gaussian-like array:")
print(gaussian_array)

2D Gaussian-like array:
[[2.06115362e-09 3.72665317e-06 4.53999298e-05 3.72665317e-06
  2.06115362e-09]
 [3.72665317e-06 6.73794700e-03 8.20849986e-02 6.73794700e-03
  3.72665317e-06]
 [4.53999298e-05 8.20849986e-02 1.00000000e+00 8.20849986e-02
  4.53999298e-05]
 [3.72665317e-06 6.73794700e-03 8.20849986e-02 6.73794700e-03
  3.72665317e-06]
 [2.06115362e-09 3.72665317e-06 4.53999298e-05 3.72665317e-06
  2.06115362e-09]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [58]:
p = 5  
array_shape = (5, 5)  

array = np.zeros(array_shape, dtype=int)
indices = np.random.choice(array.size, p, replace=False)
array[np.unravel_index(indices, array.shape)] = 1

print("2D array with randomly placed elements:")
print(array)

2D array with randomly placed elements:
[[0 0 1 0 0]
 [0 0 0 0 1]
 [1 1 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [59]:
matrix = np.random.rand(5, 5)  
row_means = matrix.mean(axis=1, keepdims=True)
result = matrix - row_means
print("Original matrix:\n", matrix)
print("Matrix after subtracting row means:\n", result)

Original matrix:
 [[0.88679771 0.8508962  0.00730963 0.80735229 0.20027707]
 [0.04157582 0.45336167 0.36458603 0.34897538 0.65342987]
 [0.64520437 0.57319361 0.76374257 0.90589084 0.65283418]
 [0.32091461 0.82253604 0.70117844 0.95073754 0.312959  ]
 [0.49441287 0.02075526 0.48627943 0.4462424  0.34230628]]
Matrix after subtracting row means:
 [[ 0.33627113  0.30036962 -0.54321695  0.25682571 -0.35024951]
 [-0.33080993  0.08097591 -0.00779972 -0.02341037  0.28104411]
 [-0.06296875 -0.1349795   0.05556946  0.19771773 -0.05533894]
 [-0.30075052  0.20087092  0.07951331  0.32907241 -0.30870612]
 [ 0.13641362 -0.33724399  0.12828019  0.08824315 -0.01569297]]


#### 59. How to sort an array by the nth column? (★★☆)

In [60]:
array = np.random.randint(0, 100, (5, 5)) 
n = 2 

sorted_array = array[array[:, n].argsort()]
print("Original array:\n", array)
print(f"Array sorted by column {n}:\n", sorted_array)

Original array:
 [[65 84  1 86  5]
 [44 79 59 68 23]
 [72 51 34 84 97]
 [ 2 74 44 95 66]
 [70  9 39 16 56]]
Array sorted by column 2:
 [[65 84  1 86  5]
 [72 51 34 84 97]
 [70  9 39 16 56]
 [ 2 74 44 95 66]
 [44 79 59 68 23]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [61]:
null_columns = np.all(array == 0, axis=0)
has_null_columns = np.any(null_columns)

print("Null columns:", null_columns)
print("Does the array have null columns?", has_null_columns)

Null columns: [False False False False False]
Does the array have null columns? False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [62]:
nearest_value = vector[np.abs(vector - scalar).argmin()]
print("Nearest value to", scalar, "in the array:", nearest_value)

Nearest value to 0.5 in the array: 0.5141411853868224


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [63]:
array1 = np.arange(3).reshape(1, 3)
array2 = np.arange(3).reshape(3, 1)

result = np.empty((3, 3), dtype=int)
with np.nditer([array1, array2, result], flags=['external_loop'], op_flags=[['readonly'], ['readonly'], ['writeonly']]) as it:
    for x, y, z in it:
        z[...] = x + y

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Resultant Sum:\n", result)

Array 1:
 [[0 1 2]]
Array 2:
 [[0]
 [1]
 [2]]
Resultant Sum:
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [65]:
import numpy as np

class NamedArray(np.ndarray):
    def __new__(cls, input_array, name="Unnamed"):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "Unnamed")


data = np.arange(10)
named_array = NamedArray(data, name="MyArray")
print("Array Name:", named_array.name)
print("Array Data:", named_array)

Array Name: MyArray
Array Data: [0 1 2 3 4 5 6 7 8 9]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [66]:
vector = np.zeros(10, dtype=int)
indices = np.random.randint(0, len(vector), 20)
np.add.at(vector, indices, 1)

print("Vector:", vector)
print("Indices:", indices)

Vector: [1 1 3 4 3 1 3 2 2 0]
Indices: [7 8 3 2 6 6 3 4 2 5 1 4 4 3 2 3 6 8 0 7]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [67]:
X = np.random.randint(1, 10, 10)  
I = np.random.randint(0, 5, 10)   
F = np.zeros(5, dtype=int)        

np.add.at(F, I, X)

print("Vector X:", X)
print("Index list I:", I)
print("Accumulated array F:", F)

Vector X: [2 9 3 8 2 3 9 8 7 7]
Index list I: [1 0 0 1 4 1 1 0 3 3]
Accumulated array F: [20 22  0 14  2]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [68]:
image = np.random.randint(0, 256, (100, 100, 3), dtype=np.uint8)  
reshaped_image = image.reshape(-1, 3)

unique_colors = np.unique(reshaped_image, axis=0)
num_unique_colors = unique_colors.shape[0]

print("Number of unique colors:", num_unique_colors)

Number of unique colors: 9997


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [69]:
array_4d = np.random.rand(3, 4, 5, 6) 
sum_over_last_two_axes = array_4d.sum(axis=(-2, -1))

print("Original 4D array shape:", array_4d.shape)
print("Sum over the last two axes shape:", sum_over_last_two_axes.shape)
print("Result:\n", sum_over_last_two_axes)

Original 4D array shape: (3, 4, 5, 6)
Sum over the last two axes shape: (3, 4)
Result:
 [[16.98602847 15.53962086 14.24964945 18.35341889]
 [14.41663131 14.45338277 15.94149305 14.26212386]
 [13.29469711 14.27943608  9.59836452 15.64568043]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [70]:
D = np.random.rand(10)  
S = np.random.randint(0, 3, 10)  

means = np.zeros(S.max() + 1)
np.add.at(means, S, D)
counts = np.bincount(S)
means /= counts

print("Vector D:", D)
print("Subset indices S:", S)
print("Means of subsets:", means)

Vector D: [0.99992249 0.19278105 0.02643056 0.43598603 0.06984657 0.18015631
 0.39582868 0.47133459 0.11314221 0.59279711]
Subset indices S: [0 2 1 1 0 1 2 0 0 0]
Means of subsets: [0.44940859 0.21419097 0.29430486]


#### 69. How to get the diagonal of a dot product? (★★★)

In [71]:
diagonal = np.einsum('ij,ji->i', x[:, None] * y, z[:, None])
print("Diagonal of the dot product:", diagonal)

Diagonal of the dot product: [ 0 18 36]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [72]:
original_vector = np.array([1, 2, 3, 4, 5])
new_vector = np.zeros(len(original_vector) + (len(original_vector) - 1) * 3, dtype=int)
new_vector[::4] = original_vector
print("New vector with interleaved zeros:", new_vector)

New vector with interleaved zeros: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [74]:
array_3d = np.random.rand(5, 5, 3)
array_2d = np.random.rand(5, 5)

result = array_3d * array_2d[:, :, None]

print("3D Array:\n", array_3d)
print("2D Array:\n", array_2d)
print("Resultant Array:\n", result)

3D Array:
 [[[0.85981724 0.70572405 0.4317072 ]
  [0.11994597 0.52080815 0.69264212]
  [0.7267197  0.56472827 0.5357957 ]
  [0.72272956 0.0249245  0.0063597 ]
  [0.76786546 0.14351561 0.62707158]]

 [[0.4902142  0.59112195 0.14533556]
  [0.31765418 0.76130505 0.61067927]
  [0.6858947  0.29239374 0.07281802]
  [0.91747279 0.04591438 0.11948672]
  [0.10917689 0.65539908 0.55660641]]

 [[0.31606811 0.21006758 0.53945897]
  [0.25057644 0.81805087 0.61749822]
  [0.89751384 0.39526872 0.09547108]
  [0.53217145 0.86331119 0.23140469]
  [0.97731378 0.0960895  0.8369954 ]]

 [[0.59812419 0.28022015 0.78606168]
  [0.83997422 0.41137334 0.7062349 ]
  [0.83140136 0.19564168 0.04370263]
  [0.57227711 0.38368142 0.78651498]
  [0.10631927 0.07117422 0.33411136]]

 [[0.40046478 0.67466453 0.66463914]
  [0.02433485 0.08578706 0.08640332]
  [0.37645536 0.4108242  0.47898809]
  [0.18082977 0.14502781 0.14790542]
  [0.97202487 0.98781816 0.60683182]]]
2D Array:
 [[0.7648651  0.42838697 0.92305664 0.411581

#### 72. How to swap two rows of an array? (★★★)

In [73]:
array = np.arange(25).reshape(5, 5)
row1, row2 = 1, 3  

array[[row1, row2]] = array[[row2, row1]]

print("Array after swapping rows:")
print(array)

Array after swapping rows:
[[ 0  1  2  3  4]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [75]:
import numpy as np

triangles = np.random.randint(0, 20, (10, 3))
segments = np.sort(np.array([[triangle[i], triangle[j]] for triangle in triangles for i in range(3) for j in range(i+1, 3)]), axis=1)
unique_segments = np.unique(segments, axis=0)

print("Triangles:\n", triangles)
print("Unique line segments:\n", unique_segments)

Triangles:
 [[11  2  8]
 [ 7 15 17]
 [ 1  3  4]
 [16 12 19]
 [ 0 13  5]
 [ 7  8  8]
 [ 9 15  6]
 [16 14  8]
 [11 16 18]
 [ 3 17 12]]
Unique line segments:
 [[ 0  5]
 [ 0 13]
 [ 1  3]
 [ 1  4]
 [ 2  8]
 [ 2 11]
 [ 3  4]
 [ 3 12]
 [ 3 17]
 [ 5 13]
 [ 6  9]
 [ 6 15]
 [ 7  8]
 [ 7 15]
 [ 7 17]
 [ 8  8]
 [ 8 11]
 [ 8 14]
 [ 8 16]
 [ 9 15]
 [11 16]
 [11 18]
 [12 16]
 [12 17]
 [12 19]
 [14 16]
 [15 17]
 [16 18]
 [16 19]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [76]:
C = np.array([4, 2, 0, 3, 1])  
A = np.repeat(np.arange(len(C)), C)
print("Array C (bincount):", C)
print("Array A:", A)

Array C (bincount): [4 2 0 3 1]
Array A: [0 0 0 0 1 1 3 3 3 4]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [77]:
array = np.arange(10)  
window_size = 3 

averages = np.convolve(array, np.ones(window_size) / window_size, mode='valid')

print("Original array:", array)
print("Sliding window averages:", averages)

Original array: [0 1 2 3 4 5 6 7 8 9]
Sliding window averages: [1. 2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [78]:
Z = np.arange(10)  
rows = len(Z) - 2  
result = np.array([Z[i:i+3] for i in range(rows)])

print("Original array:", Z)
print("Resultant 2D array:")
print(result)

Original array: [0 1 2 3 4 5 6 7 8 9]
Resultant 2D array:
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [79]:
bool_array = np.array([True, False, True, False], dtype=bool)
np.logical_not(bool_array, out=bool_array)
print("Negated boolean array:", bool_array)
float_array = np.array([1.0, -2.0, 3.0, -4.0], dtype=float)
float_array *= -1
print("Sign-changed float array:", float_array)

Negated boolean array: [False  True False  True]
Sign-changed float array: [-1.  2. -3.  4.]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [80]:
P0 = np.array([[0, 0], [1, 1], [2, 2]]) 
P1 = np.array([[1, 0], [2, 1], [3, 2]]) 
p = np.array([0, 2]) 

line_vectors = P1 - P0
point_vectors = P0 - p
cross_products = np.abs(line_vectors[:, 0] * point_vectors[:, 1] - line_vectors[:, 1] * point_vectors[:, 0])
line_lengths = np.linalg.norm(line_vectors, axis=1)
distances = cross_products / line_lengths

print("Distances from point to each line:", distances)

Distances from point to each line: [2. 1. 0.]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [81]:
P0 = np.array([[0, 0], [1, 1], [2, 2]]) 
P1 = np.array([[1, 0], [2, 1], [3, 2]]) 
P = np.array([[0, 2], [2, 0], [1, 1]])  

line_vectors = P1 - P0
point_vectors = P[:, None, :] - P0[None, :, :]
cross_products = np.abs(line_vectors[:, 0] * point_vectors[:, :, 1] - line_vectors[:, 1] * point_vectors[:, :, 0])
line_lengths = np.linalg.norm(line_vectors, axis=1)
distances = cross_products / line_lengths

print("Distances from each point to each line:")
print(distances)

Distances from each point to each line:
[[2. 1. 0.]
 [0. 1. 2.]
 [1. 0. 1.]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [82]:
def extract_subarray(array, center, shape, fill=0):
    slices = []
    padding = []
    for dim, (c, s) in enumerate(zip(center, shape)):
        start = c - s // 2
        end = c + s // 2 + 1
        pad_before = max(0, -start)
        pad_after = max(0, end - array.shape[dim])
        slices.append(slice(max(0, start), min(array.shape[dim], end)))
        padding.append((pad_before, pad_after))
    
    subarray = array[tuple(slices)]
    if any(pad_before > 0 or pad_after > 0 for pad_before, pad_after in padding):
        subarray = np.pad(subarray, padding, mode='constant', constant_values=fill)
    
    return subarray

# Example usage
array = np.arange(25).reshape(5, 5)
center = (2, 2)
shape = (3, 3)
fill = -1

result = extract_subarray(array, center, shape, fill)
print("Original array:\n", array)
print("Extracted subarray:\n", result)

Original array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Extracted subarray:
 [[ 6  7  8]
 [11 12 13]
 [16 17 18]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [83]:
Z = np.arange(1, 15)  
window_size = 4  

R = np.lib.stride_tricks.sliding_window_view(Z, window_size)
print("Generated array R:")
print(R)

Generated array R:
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [84]:
matrix = np.random.rand(5, 5)  

rank = np.linalg.matrix_rank(matrix)

print("Matrix:\n", matrix)
print("Rank of the matrix:", rank)

Matrix:
 [[0.64911142 0.04347578 0.57987819 0.47541824 0.41962522]
 [0.30983467 0.114358   0.7476754  0.02170039 0.81125799]
 [0.78173836 0.12404806 0.60841259 0.24960018 0.99244568]
 [0.79002065 0.53694852 0.08051455 0.02695849 0.73990952]
 [0.0736531  0.66314929 0.25860449 0.70035473 0.33218756]]
Rank of the matrix: 5


#### 83. How to find the most frequent value in an array?

In [85]:
values, counts = np.unique(vector, return_counts=True)
most_frequent_value = values[np.argmax(counts)]

print("Most frequent value:", most_frequent_value)

Most frequent value: 1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [86]:
matrix = np.random.rand(10, 10)  
blocks = np.lib.stride_tricks.sliding_window_view(matrix, (3, 3))

print("Original 10x10 matrix:\n", matrix)
print("Contiguous 3x3 blocks:\n", blocks)

Original 10x10 matrix:
 [[0.21656261 0.10008549 0.71481523 0.2542261  0.07077404 0.5087019
  0.62826545 0.59822858 0.16480612 0.13096087]
 [0.39129008 0.00426397 0.19612276 0.93241782 0.07865254 0.6109063
  0.53603029 0.1405764  0.73733075 0.5772594 ]
 [0.48141737 0.68750283 0.47262891 0.81175645 0.76467404 0.66704329
  0.79237883 0.12530127 0.56659411 0.06819395]
 [0.22869742 0.17159851 0.82350218 0.44142416 0.60719868 0.08291204
  0.93083072 0.89916485 0.94646508 0.46810042]
 [0.16456183 0.90088833 0.28301792 0.6093545  0.58812117 0.06337615
  0.12371076 0.06174062 0.93966189 0.33661368]
 [0.03691883 0.38046785 0.07978854 0.26892917 0.02894234 0.80028844
  0.5764024  0.55348165 0.07877978 0.10882533]
 [0.76471477 0.72501836 0.74609244 0.49622596 0.14508012 0.73478431
  0.16935848 0.03297491 0.46834918 0.12075446]
 [0.2664489  0.80310875 0.49379691 0.76487206 0.54728133 0.78408012
  0.13878701 0.77642401 0.54321428 0.19806523]
 [0.46400986 0.40148281 0.76816009 0.26562356 0.2034342  0

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [87]:
class SymmetricArray(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(SymmetricArray, self).__setitem__((i, j), value)
        super(SymmetricArray, self).__setitem__((j, i), value)


size = 5
Z = np.zeros((size, size)).view(SymmetricArray)
Z[2, 3] = 10

print("Symmetric array:")
print(Z)

Symmetric array:
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [88]:
p, n = 3, 4 
matrices = np.random.rand(p, n, n)  
vectors = np.random.rand(p, n, 1)  

result = np.einsum('pij,pjk->ik', matrices, vectors)

print("Set of matrices:\n", matrices)
print("Set of vectors:\n", vectors)
print("Resultant sum of matrix products:\n", result)

Set of matrices:
 [[[0.80547087 0.46977416 0.75007904 0.35727768]
  [0.74083052 0.02068152 0.91993248 0.35914404]
  [0.18591293 0.10695594 0.37459291 0.77173033]
  [0.78591037 0.0481882  0.45830143 0.55827907]]

 [[0.80094937 0.33506041 0.60057992 0.14578005]
  [0.94747992 0.39446808 0.66125905 0.14900556]
  [0.73923831 0.21440441 0.56525031 0.26265881]
  [0.30511527 0.78942919 0.76221711 0.37819019]]

 [[0.31779053 0.75697825 0.41868925 0.26703457]
  [0.55353205 0.93341076 0.13452853 0.36052875]
  [0.64343177 0.25634568 0.78671385 0.10447023]
  [0.17197374 0.66735162 0.24035121 0.36981401]]]
Set of vectors:
 [[[0.78617899]
  [0.29131723]
  [0.16203361]
  [0.22530716]]

 [[0.91356886]
  [0.44743912]
  [0.11360948]
  [0.13630096]]

 [[0.55884665]
  [0.2882314 ]
  [0.95688695]
  [0.54884774]]]
Resultant sum of matrix products:
 [[2.88485656]
 [2.86093329]
 [2.52678946]
 [2.32347603]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [89]:
array_16x16 = np.random.rand(16, 16)  
block_size = 4

block_sum = array_16x16.reshape(16 // block_size, block_size, 16 // block_size, block_size).sum(axis=(1, 3))

print("Original 16x16 array:\n", array_16x16)
print("Block-sum (4x4):\n", block_sum)

Original 16x16 array:
 [[0.22540408 0.25275933 0.67797469 0.64672695 0.98367595 0.40329194
  0.77319514 0.11658009 0.26494733 0.47443159 0.47260328 0.66477217
  0.76726159 0.21856695 0.93044908 0.52779446]
 [0.59059271 0.64063922 0.80485307 0.39274237 0.48347666 0.47354807
  0.09725617 0.95656304 0.35598913 0.31795287 0.13465136 0.74057832
  0.30616285 0.21830545 0.26131867 0.9587276 ]
 [0.1905292  0.3055669  0.80971675 0.22890103 0.77531944 0.63589178
  0.03707196 0.31237649 0.24135082 0.08805449 0.97175372 0.45979016
  0.40505389 0.52140601 0.54353125 0.32155173]
 [0.53948885 0.77576069 0.97654248 0.37096657 0.35133757 0.1902323
  0.26015795 0.48996705 0.11868458 0.69413842 0.81664951 0.26763286
  0.69119548 0.10524167 0.77712328 0.37722961]
 [0.04808147 0.15812091 0.72618681 0.7964673  0.51972487 0.35469481
  0.76709164 0.43572714 0.42129702 0.45061538 0.51111687 0.0835533
  0.07222697 0.35728272 0.14886374 0.29748409]
 [0.74961958 0.12317147 0.1823959  0.06373937 0.08630074 0.58259

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [90]:
import numpy as np

def game_of_life_step(board):
   
    neighbors = sum(np.roll(np.roll(board, i, 0), j, 1)
                    for i in (-1, 0, 1) for j in (-1, 0, 1)
                    if (i != 0 or j != 0))
    
    
    new_board = (neighbors == 3) | ((board == 1) & (neighbors == 2))
    return new_board.astype(int)


np.random.seed(0)
board = np.random.randint(2, size=(10, 10))

print("Initial Board:")
print(board)
board = game_of_life_step(board)

print("Next Generation:")
print(board)

Initial Board:
[[0 1 1 0 1 1 1 1 1 1]
 [1 0 0 1 0 0 0 0 0 1]
 [0 1 1 0 0 1 1 1 1 0]
 [1 0 1 0 1 1 0 1 1 0]
 [0 1 0 1 1 1 1 1 0 1]
 [0 1 1 1 1 0 1 0 0 1]
 [1 0 1 0 1 0 0 0 0 0]
 [1 1 0 0 0 1 1 0 1 0]
 [0 1 0 1 1 1 1 1 1 0]
 [1 1 0 0 1 0 0 1 1 0]]
Next Generation:
[[0 0 1 0 1 1 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 1 0 1 1 0 0]
 [1 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


C:\Users\197as\AppData\Local\Temp\ipykernel_18496\1125989881.py:5: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  neighbors = sum(np.roll(np.roll(board, i, 0), j, 1)


#### 89. How to get the n largest values of an array (★★★)

In [91]:
n = 3  
largest_values = np.partition(vector, -n)[-n:]
largest_values_sorted = np.sort(largest_values)

print(f"The {n} largest values in the array are:", largest_values_sorted)

The 3 largest values in the array are: [3 3 4]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [92]:
import numpy as np

vectors = [np.array([1, 2, 3]), np.array([4, 5]), np.array([6, 7, 8])]

cartesian_product = np.array(np.meshgrid(*vectors)).T.reshape(-1, len(vectors))

print("Cartesian product of the vectors:")
print(cartesian_product)

Cartesian product of the vectors:
[[1 4 6]
 [1 5 6]
 [2 4 6]
 [2 5 6]
 [3 4 6]
 [3 5 6]
 [1 4 7]
 [1 5 7]
 [2 4 7]
 [2 5 7]
 [3 4 7]
 [3 5 7]
 [1 4 8]
 [1 5 8]
 [2 4 8]
 [2 5 8]
 [3 4 8]
 [3 5 8]]


#### 91. How to create a record array from a regular array? (★★★)

In [93]:
import numpy as np
regular_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
record_array = np.core.records.fromarrays(regular_array.T, names='col1, col2, col3', formats='i4, i4, i4')

print("Record array:")
print(record_array)

Record array:
[(1, 2, 3) (4, 5, 6) (7, 8, 9)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [94]:
method1 = Z ** 3
method2 = np.power(Z, 3)
method3 = Z * Z * Z

print("Method 1 result:\n", method1)
print("Method 2 result:\n", method2)
print("Method 3 result:\n", method3)

Method 1 result:
 [[   0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.]
 [   0.    0.    0. 1000.    0.]
 [   0.    0. 1000.    0.    0.]
 [   0.    0.    0.    0.    0.]]
Method 2 result:
 [[   0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.]
 [   0.    0.    0. 1000.    0.]
 [   0.    0. 1000.    0.    0.]
 [   0.    0.    0.    0.    0.]]
Method 3 result:
 [[   0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.]
 [   0.    0.    0. 1000.    0.]
 [   0.    0. 1000.    0.    0.]
 [   0.    0.    0.    0.    0.]]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [95]:
A = np.random.randint(0, 10, (8, 3))
B = np.random.randint(0, 10, (2, 2))

result = []
for row in A:
    if all(any(row == b for b in B_row) for B_row in B):
        result.append(row)

result = np.array(result)

print("Array A:\n", A)
print("Array B:\n", B)
print("Rows of A containing elements of each row of B:\n", result)

Array A:
 [[9 4 4]
 [6 4 4]
 [3 4 4]
 [8 4 3]
 [7 5 5]
 [0 1 5]
 [9 3 0]
 [5 0 1]]
Array B:
 [[2 4]
 [2 0]]
Rows of A containing elements of each row of B:
 [[9 4 4]
 [6 4 4]
 [3 4 4]
 [8 4 3]
 [7 5 5]
 [0 1 5]
 [9 3 0]
 [5 0 1]]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [96]:
matrix = np.random.randint(0, 10, (10, 3))  
unequal_rows = matrix[np.all(matrix[:, 1:] != matrix[:, :-1], axis=1)]

print("Original matrix:\n", matrix)
print("Rows with unequal values:\n", unequal_rows)

Original matrix:
 [[3 2 0]
 [7 5 9]
 [0 2 7]
 [2 9 2]
 [3 3 2]
 [3 4 1]
 [2 9 1]
 [4 6 8]
 [2 3 0]
 [0 6 0]]
Rows with unequal values:
 [[3 2 0]
 [7 5 9]
 [0 2 7]
 [2 9 2]
 [3 4 1]
 [2 9 1]
 [4 6 8]
 [2 3 0]
 [0 6 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [97]:
vector = np.array([1, 2, 3, 4, 5])  
binary_matrix = ((vector[:, None] & (1 << np.arange(8))) > 0).astype(int)

print("Vector of integers:", vector)
print("Binary representation matrix:\n", binary_matrix)

Vector of integers: [1 2 3 4 5]
Binary representation matrix:
 [[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 1 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [98]:
binary_matrix = ((vector[:, None] & (1 << np.arange(8))) > 0).astype(int)

print("Vector of integers:", vector)
print("Binary representation matrix:\n", binary_matrix)

Vector of integers: [1 2 3 4 5]
Binary representation matrix:
 [[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 1 0 0 0 0 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [100]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

inner_product = np.einsum('i,i->', A, B)
print("Inner product:", inner_product)

outer_product = np.einsum('i,j->ij', A, B)
print("Outer product:\n", outer_product)

sum_elements = np.einsum('i->', A)
print("Sum of elements in A:", sum_elements)

elementwise_mul = np.einsum('i,i->i', A, B)
print("Element-wise multiplication:", elementwise_mul)

Inner product: 32
Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum of elements in A: 6
Element-wise multiplication: [ 4 10 18]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [102]:
import numpy as np

X = np.array([0, 1, 2, 3, 4])
Y = np.array([0, 1, 0, 1, 0])

num_samples = 10

distances = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)
cumulative_distances = np.insert(np.cumsum(distances), 0, 0)

equidistant_points = np.linspace(0, cumulative_distances[-1], num_samples)
X_sampled = np.interp(equidistant_points, cumulative_distances, X)
Y_sampled = np.interp(equidistant_points, cumulative_distances, Y)

print("Sampled X coordinates:", X_sampled)
print("Sampled Y coordinates:", Y_sampled)

Sampled X coordinates: [0.         0.44444444 0.88888889 1.33333333 1.77777778 2.22222222
 2.66666667 3.11111111 3.55555556 4.        ]
Sampled Y coordinates: [0.         0.44444444 0.88888889 0.66666667 0.22222222 0.22222222
 0.66666667 0.88888889 0.44444444 0.        ]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [103]:
n = 10
X = np.random.randint(0, 10, (10, 5))  

valid_rows = X[np.all(X >= 0, axis=1) & (X.sum(axis=1) == n)]

print("Original array X:\n", X)
print(f"Rows that can be interpreted as draws from a multinomial distribution with n={n}:\n", valid_rows)

Original array X:
 [[6 3 3 8 8]
 [8 2 3 2 0]
 [8 8 3 8 2]
 [8 4 3 0 4]
 [3 6 9 8 0]
 [8 5 9 0 9]
 [6 5 3 1 8]
 [0 4 9 6 5]
 [7 8 8 9 2]
 [8 6 6 9 1]]
Rows that can be interpreted as draws from a multinomial distribution with n=10:
 []


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [104]:
import numpy as np

X = np.random.rand(100) 
N = 1000  

bootstrap_means = np.array([np.mean(np.random.choice(X, size=len(X), replace=True)) for _ in range(N)])
confidence_interval = np.percentile(bootstrap_means, [2.5, 97.5])

print("Bootstrap 95% confidence interval for the mean:", confidence_interval)

Bootstrap 95% confidence interval for the mean: [0.44311344 0.55539226]
